version: CI-Build-{build}
max_jobs: 1
branches:
  except:
    - gh-pages
image: Visual Studio 2017

install:
  - git submodule update --init --recursive

before_build:
  - nuget restore Telegram.Bot.Extensions.Passport.sln

build:
  project: Telegram.Bot.Extensions.Passport.sln
  publish_nuget: true

test:
  assemblies:
    only:
      - '**\UnitTests.dll'

nuget:
  disable_publish_on_pr: true

deploy:
  - provider: NuGet
    api_key:
      secure: TO_DO
    on:
      branch: master


for:
-
  branches:
    only:
      - master
  configuration: Release
-
  branches:
    except:
      - master
  configuration: Debug
