branches:
  except:
    - gh-pages
image: Visual Studio 2017

install:
  - git submodule update --init --recursive

before_build:
  - nuget restore Telegram.Bot.Extensions.Passport.sln

build:
  project: Telegram.Bot.Extensions.Passport.sln
  publish_nuget: true

test:
  assemblies:
# run unit tests only in a Windows environment
    only:
      - '**\UnitTests.dll'

nuget:
  disable_publish_on_pr: true

deploy:
  - provider: NuGet
    artifact: /.*Telegram.Bot.Extensions.Passport.*\.nupkg/
    api_key:
      secure: HHTe2/56sywbQ4uGD1fOeOBWjggVknMVXKhBu7978+LPJQCLJ28Ji9suN7nIfSGY
    on:
      branch: master


for:
-
  branches:
    only:
      - master
      - develop
  configuration: Release
