language: csharp
dist: trusty
sudo: false
mono: none
dotnet: 2.0.0
branches:
  except:
  - master
script: >
  cd test/IntegrationTests &&
  dotnet test --configuration Release --list-tests &&
  dotnet xunit -configuration Release -nobuild -stoponfail -verbose
notifications:
  email: false

## Notes:
### Limit concurrent jobs to only 1
### Disable building PRs (might expose env vars)

## Environment Variables:

# TelegramBot_ApiToken                      test-bot-api-token
# TelegramBot_AllowedUserNames              main_tester,some_other_user
# TelegramBot_SuperGroupChatId              -1234
