dist: trusty
services:
  - docker
branches:
  except:
  - master
  - gh-pages
notifications:
  email: false
install:
  - docker pull microsoft/dotnet:2.0.0-sdk-stretch
  - cd ci && npm install && cd -
script:
  - node ci/travis-ci.js


## Notes:
### Disable building PRs (might expose env vars)

## Environment Variables:

# TelegramBot_ApiToken                      test-bot-api-token
# TelegramBot_AllowedUserNames              main_tester,some_other_user
# TelegramBot_SuperGroupChatId              -1234
